apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "healthos.fullname" . }}-api
  labels:
    {{- include "healthos.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "healthos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "healthos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ include "healthos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.api.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.secretRef }}
          livenessProbe:
            httpGet:
              path: {{ .Values.api.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.api.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.healthCheck.periodSeconds }}
            failureThreshold: {{ .Values.api.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.api.healthCheck.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
