apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "healthos.fullname" . }}-config
  labels:
    {{- include "healthos.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  API_PORT: {{ .Values.api.port | quote }}
  LOG_LEVEL: {{ .Values.api.env.LOG_LEVEL | default "info" | quote }}
  PROMETHEUS_ENABLED: "true"
  KAFKA_TOPICS_VITALS: "healthos.vitals.ingested"
  KAFKA_TOPICS_ALERTS: "healthos.alerts.generated"
  KAFKA_TOPICS_AGENT_EVENTS: "healthos.agent.events"
